name: Build and Push Image
on: [push]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login to container registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "${{ secrets.CR_USERNAME }}" --password-stdin

      - name: Build image with Makefile
        run: make image-build

      - name: Push image with Makefile
        run: make image-push
